In [1]:
a = [1,2]
b = [3,4]

In [2]:
# a*b it gives me error == can't multiply sequence by non-int of type 'list'

In [3]:
# a/b #it gives me error == unsupported operand type(s) for /: 'list' and 'list'

In [4]:
 import numpy as np   # np is alice used for numpy

## 1D Array

In [5]:
one_D = np.array([1,2,3,4,5,6,7,8])
one_D

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
one_D.ndim

1

In [7]:
one_D.size  # no of element present in array

8

In [8]:
one_D.max()

8

In [9]:
one_D.min()

1

In [10]:
one_D.sum()

36

In [11]:
one_D[2]

3

In [12]:
one_D.dtype

dtype('int32')

In [13]:
one_D = np.array([1,2,3,4,5,6,7,9.5])

In [14]:
one_D.dtype

dtype('float64')

In [15]:
one_D

array([1. , 2. , 3. , 4. , 5. , 6. , 7. , 9.5])

In [16]:
one_D[7] = 8

In [17]:
one_D

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [18]:
one_D[4:7]

array([5., 6., 7.])

In [19]:
one_D[4:7] = [55,66,77]

In [20]:
one_D

array([ 1.,  2.,  3.,  4., 55., 66., 77.,  8.])

In [21]:
c = np.delete(one_D,[5,6,7])  # Temperary delet the data
                   # Delet with only index number

In [22]:
one_D

array([ 1.,  2.,  3.,  4., 55., 66., 77.,  8.])

In [23]:
a = np.append(one_D,[100,200])  # Temporary add the data at the last of array
a                              # add with only index number

array([  1.,   2.,   3.,   4.,  55.,  66.,  77.,   8., 100., 200.])

In [24]:
one_D

array([ 1.,  2.,  3.,  4., 55., 66., 77.,  8.])

In [25]:
s = np.insert(one_D,4,44)
s

array([ 1.,  2.,  3.,  4., 44., 55., 66., 77.,  8.])

In [26]:
one_D

array([ 1.,  2.,  3.,  4., 55., 66., 77.,  8.])

In [27]:
one_D.mean()

27.0

In [28]:
one_D.nbytes

64

In [29]:
a = np.array([6,8,10])
b = np.array([2,4,6])


In [30]:
a*b

array([12, 32, 60])

In [31]:
a/b

array([3.        , 2.        , 1.66666667])

## Two Dimensional Array

In [32]:
two_dim = np.array([[1,2,3],[4,5,6,],[7,8,9]]) 

In [33]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
two_dim[0][1]

2

In [35]:
two_dim[2,2]

9

In [36]:
two_dim[1]  # Access 1st Row

array([4, 5, 6])

In [37]:
two_dim[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
two_dim[:,1:2]  # Only column access

array([[2],
       [5],
       [8]])

In [39]:
two_dim[:,0::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [40]:
two_dim[1,[0,2]]

array([4, 6])

In [41]:
two_dim[1:,1:2]

array([[5],
       [8]])

In [42]:
type(two_dim)

numpy.ndarray

In [43]:
two_dim.ndim

2

In [44]:
two_dim.nbytes

36

In [45]:
two_dim.size

9

In [46]:
two_dim.shape

(3, 3)

In [47]:
two_dim.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
np.unique(two_dim)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
two_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
two_dim[2,1] =70

In [51]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 70,  9]])

In [52]:
np.insert(two_dim,2,[70,80,90])

array([ 1,  2, 70, 80, 90,  3,  4,  5,  6,  7, 70,  9])

In [53]:
np.insert(two_dim,3,[70,80,90],axis=0)  # Rowwise performance = 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 70,  9],
       [70, 80, 90]])

In [54]:
np.insert(two_dim,3,[70,80,90],axis=1) # Columnwise performance = 1

array([[ 1,  2,  3, 70],
       [ 4,  5,  6, 80],
       [ 7, 70,  9, 90]])

In [55]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 70,  9]])

In [56]:
np.append(two_dim,np.array([[100,200,300]]),axis = 0)

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,  70,   9],
       [100, 200, 300]])

In [57]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 70,  9]])

In [58]:
np.append(two_dim,np.array([[100],[200],[300]]),axis = 1)  # for column use individual square

array([[  1,   2,   3, 100],
       [  4,   5,   6, 200],
       [  7,  70,   9, 300]])

In [59]:
two_dim

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 70,  9]])

### 2D to 1D-> C= Rowwise operatopn, F = Columnwise operation

# by ravel function

In [60]:
np.ravel(two_dim,order='F')

array([ 1,  4,  7,  2,  5, 70,  3,  6,  9])

In [61]:
np.ravel(two_dim,order='C')

array([ 1,  2,  3,  4,  5,  6,  7, 70,  9])

# by reshape method

In [62]:
two_dim.reshape(-1,order='F')          ## 2d = -1 for 1d 

array([ 1,  4,  7,  2,  5, 70,  3,  6,  9])

In [63]:
two_dim.reshape(-1,order='C')

array([ 1,  2,  3,  4,  5,  6,  7, 70,  9])

# arrange

### Generate 1D

In [64]:
one_D = np.arange(1,10)

In [65]:
one_D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
one_D.ndim

1

### Generate 2d

In [67]:
two_D = np.arange(1,10).reshape(3,3)
two_D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Random Array 1D

In [68]:
np.random.rand(10)   # it gives 10 nos of random number, values between 0 to 1 

array([0.62556897, 0.98583818, 0.08732776, 0.18521791, 0.18186427,
       0.31813848, 0.06166992, 0.10826319, 0.69668795, 0.34778944])

In [69]:
np.random.rand(10).ndim

1

# Random Array 2D


In [70]:
np.random.rand(4,4)  # it give 4*4 Matrix

array([[0.99620892, 0.64504657, 0.05729573, 0.16961699],
       [0.84216704, 0.83131674, 0.80434212, 0.50266046],
       [0.34556623, 0.27000503, 0.39306685, 0.79185062],
       [0.20745591, 0.05850269, 0.52891747, 0.13144981]])

# generate int number

### 1D

In [71]:
np.random.randint(1,100)

99

In [72]:
np.random.randint(1,100,12)  # I want 12 number , values between 1 to 100

array([49, 54, 64, 68, 10, 26, 59, 63, 54, 17,  4, 34])

#### 2D

In [73]:
np.random.randint(-9,100,12).reshape(4,3)

array([[84, 72, -5],
       [48, 79, 55],
       [26, 16, 98],
       [24, 16, 30]])

# Linspace

In [74]:
# Generate float 1D

In [75]:
np.linspace(-3,10,10)

array([-3.        , -1.55555556, -0.11111111,  1.33333333,  2.77777778,
        4.22222222,  5.66666667,  7.11111111,  8.55555556, 10.        ])

In [76]:
z = np.linspace(0,10,30).reshape(10,3).round(3)
z

array([[ 0.   ,  0.345,  0.69 ],
       [ 1.034,  1.379,  1.724],
       [ 2.069,  2.414,  2.759],
       [ 3.103,  3.448,  3.793],
       [ 4.138,  4.483,  4.828],
       [ 5.172,  5.517,  5.862],
       [ 6.207,  6.552,  6.897],
       [ 7.241,  7.586,  7.931],
       [ 8.276,  8.621,  8.966],
       [ 9.31 ,  9.655, 10.   ]])

In [77]:
# Delet specific row

In [78]:
np.delete(z,1,axis = 1)

array([[ 0.   ,  0.69 ],
       [ 1.034,  1.724],
       [ 2.069,  2.759],
       [ 3.103,  3.793],
       [ 4.138,  4.828],
       [ 5.172,  5.862],
       [ 6.207,  6.897],
       [ 7.241,  7.931],
       [ 8.276,  8.966],
       [ 9.31 , 10.   ]])

In [79]:
z

array([[ 0.   ,  0.345,  0.69 ],
       [ 1.034,  1.379,  1.724],
       [ 2.069,  2.414,  2.759],
       [ 3.103,  3.448,  3.793],
       [ 4.138,  4.483,  4.828],
       [ 5.172,  5.517,  5.862],
       [ 6.207,  6.552,  6.897],
       [ 7.241,  7.586,  7.931],
       [ 8.276,  8.621,  8.966],
       [ 9.31 ,  9.655, 10.   ]])

In [80]:
np.delete(z,[1,2],axis = 1)

array([[0.   ],
       [1.034],
       [2.069],
       [3.103],
       [4.138],
       [5.172],
       [6.207],
       [7.241],
       [8.276],
       [9.31 ]])

In [81]:
z

array([[ 0.   ,  0.345,  0.69 ],
       [ 1.034,  1.379,  1.724],
       [ 2.069,  2.414,  2.759],
       [ 3.103,  3.448,  3.793],
       [ 4.138,  4.483,  4.828],
       [ 5.172,  5.517,  5.862],
       [ 6.207,  6.552,  6.897],
       [ 7.241,  7.586,  7.931],
       [ 8.276,  8.621,  8.966],
       [ 9.31 ,  9.655, 10.   ]])

In [82]:
z.mean()

4.999999999999999

In [83]:
z.mean(axis = 0) 

array([4.655, 5.   , 5.345])

In [84]:
z.mean(axis = 1)

array([0.345, 1.379, 2.414, 3.448, 4.483, 5.517, 6.552, 7.586, 8.621,
       9.655])

# argmax

In [85]:
z.argmax(axis= 0)  # Highest value of row in index format

array([9, 9, 9], dtype=int64)

In [86]:
z.argmax(axis= 1)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [87]:
b = np.random.randint(10,40,4).reshape(2,2)
b

array([[35, 16],
       [25, 23]])

In [88]:
c = np.random.randint(20,90,4).reshape(2,2)
c

array([[62, 69],
       [41, 56]])

In [89]:
b+c

array([[97, 85],
       [66, 79]])

In [90]:
c-b

array([[27, 53],
       [16, 33]])

In [91]:
c*b

array([[2170, 1104],
       [1025, 1288]])

# Matrix Operation

In [92]:
b@c

array([[2826, 3311],
       [2493, 3013]])

In [93]:
b@b

array([[1625,  928],
       [1450,  929]])

In [94]:
c*c

array([[3844, 4761],
       [1681, 3136]])

# Inverse of Matrix

In [95]:
np.linalg.inv(b)

array([[ 0.05679012, -0.03950617],
       [-0.0617284 ,  0.08641975]])

# Eigen Value and Eigen vectors

In [96]:
np.linalg.eig(b)

EigResult(eigenvalues=array([49.88061302,  8.11938698]), eigenvectors=array([[ 0.73225767, -0.51147525],
       [ 0.68102769,  0.85929801]]))

In [97]:
np.linalg.eig(c)

EigResult(eigenvalues=array([112.27288241,   5.72711759]), eigenvectors=array([[ 0.80822839, -0.77495628],
       [ 0.58886914,  0.63201484]]))

# Identity Metrics

In [98]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
np.ones(shape = (4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.zeros(shape= (3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
two_D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Stacking of arrays  / combining of array /Mergig

In [103]:
b

array([[35, 16],
       [25, 23]])

In [104]:
c

array([[62, 69],
       [41, 56]])

In [105]:
np.hstack([b,c])   # Horizontal stacking

array([[35, 16, 62, 69],
       [25, 23, 41, 56]])

In [106]:
np.vstack([b,b])   # Vertical stacking

array([[35, 16],
       [25, 23],
       [35, 16],
       [25, 23]])

# Splitting  Based on Index

In [107]:
b

array([[35, 16],
       [25, 23]])

In [108]:
c

array([[62, 69],
       [41, 56]])

#### h split use to split column based on the index

In [109]:
z

array([[ 0.   ,  0.345,  0.69 ],
       [ 1.034,  1.379,  1.724],
       [ 2.069,  2.414,  2.759],
       [ 3.103,  3.448,  3.793],
       [ 4.138,  4.483,  4.828],
       [ 5.172,  5.517,  5.862],
       [ 6.207,  6.552,  6.897],
       [ 7.241,  7.586,  7.931],
       [ 8.276,  8.621,  8.966],
       [ 9.31 ,  9.655, 10.   ]])

In [110]:
np.hsplit(z,3)

[array([[0.   ],
        [1.034],
        [2.069],
        [3.103],
        [4.138],
        [5.172],
        [6.207],
        [7.241],
        [8.276],
        [9.31 ]]),
 array([[0.345],
        [1.379],
        [2.414],
        [3.448],
        [4.483],
        [5.517],
        [6.552],
        [7.586],
        [8.621],
        [9.655]]),
 array([[ 0.69 ],
        [ 1.724],
        [ 2.759],
        [ 3.793],
        [ 4.828],
        [ 5.862],
        [ 6.897],
        [ 7.931],
        [ 8.966],
        [10.   ]])]

In [111]:
np.hsplit(z,[0,1])

[array([], shape=(10, 0), dtype=float64),
 array([[0.   ],
        [1.034],
        [2.069],
        [3.103],
        [4.138],
        [5.172],
        [6.207],
        [7.241],
        [8.276],
        [9.31 ]]),
 array([[ 0.345,  0.69 ],
        [ 1.379,  1.724],
        [ 2.414,  2.759],
        [ 3.448,  3.793],
        [ 4.483,  4.828],
        [ 5.517,  5.862],
        [ 6.552,  6.897],
        [ 7.586,  7.931],
        [ 8.621,  8.966],
        [ 9.655, 10.   ]])]

In [112]:
np.hsplit(z,[0,2])

[array([], shape=(10, 0), dtype=float64),
 array([[0.   , 0.345],
        [1.034, 1.379],
        [2.069, 2.414],
        [3.103, 3.448],
        [4.138, 4.483],
        [5.172, 5.517],
        [6.207, 6.552],
        [7.241, 7.586],
        [8.276, 8.621],
        [9.31 , 9.655]]),
 array([[ 0.69 ],
        [ 1.724],
        [ 2.759],
        [ 3.793],
        [ 4.828],
        [ 5.862],
        [ 6.897],
        [ 7.931],
        [ 8.966],
        [10.   ]])]

#### v split use to split rows based on the index

In [113]:
np.vsplit(z,5)

[array([[0.   , 0.345, 0.69 ],
        [1.034, 1.379, 1.724]]),
 array([[2.069, 2.414, 2.759],
        [3.103, 3.448, 3.793]]),
 array([[4.138, 4.483, 4.828],
        [5.172, 5.517, 5.862]]),
 array([[6.207, 6.552, 6.897],
        [7.241, 7.586, 7.931]]),
 array([[ 8.276,  8.621,  8.966],
        [ 9.31 ,  9.655, 10.   ]])]

In [114]:
np.vsplit(z,[1,4,5])


[array([[0.   , 0.345, 0.69 ]]),
 array([[1.034, 1.379, 1.724],
        [2.069, 2.414, 2.759],
        [3.103, 3.448, 3.793]]),
 array([[4.138, 4.483, 4.828]]),
 array([[ 5.172,  5.517,  5.862],
        [ 6.207,  6.552,  6.897],
        [ 7.241,  7.586,  7.931],
        [ 8.276,  8.621,  8.966],
        [ 9.31 ,  9.655, 10.   ]])]

# 3D Array

In [115]:
thrre_D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [116]:
thrre_D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [117]:
thrre_D.ndim

3

In [118]:
thrre_D.shape

(2, 2, 2)

In [119]:
thrre_D[1,1,1]

8

In [120]:
thrre_D = np.array([[[1,2,3],[3,4,4]],[[7,5,6],[9,7,8]]])

In [121]:
thrre_D

array([[[1, 2, 3],
        [3, 4, 4]],

       [[7, 5, 6],
        [9, 7, 8]]])

In [122]:
thrre_D[0][0][0]

1

In [123]:
thrre_D[0,1]

array([3, 4, 4])

In [124]:
thrre_D[[0,1],1]

array([[3, 4, 4],
       [9, 7, 8]])

##### Updating

In [125]:
thrre_D[1,1,2]= 80
thrre_D

array([[[ 1,  2,  3],
        [ 3,  4,  4]],

       [[ 7,  5,  6],
        [ 9,  7, 80]]])

In [126]:
thrre_D[[0,1],:,0:1]

array([[[1],
        [3]],

       [[7],
        [9]]])

In [127]:
thrre_D

array([[[ 1,  2,  3],
        [ 3,  4,  4]],

       [[ 7,  5,  6],
        [ 9,  7, 80]]])

# Random Creation

In [130]:
thrD = np.random.randint(10,100,27).reshape(3,3,3
                                           )

In [131]:
thrD

array([[[56, 37, 70],
        [87, 74, 93],
        [17, 85, 75]],

       [[69, 79, 11],
        [95, 71, 40],
        [83, 74, 68]],

       [[17, 10, 55],
        [41, 36, 43],
        [44, 38, 26]]])

In [133]:
np.delete(thrD,1,axis = 0)  # Block 1 delet

array([[[56, 37, 70],
        [87, 74, 93],
        [17, 85, 75]],

       [[17, 10, 55],
        [41, 36, 43],
        [44, 38, 26]]])

In [134]:
thrD

array([[[56, 37, 70],
        [87, 74, 93],
        [17, 85, 75]],

       [[69, 79, 11],
        [95, 71, 40],
        [83, 74, 68]],

       [[17, 10, 55],
        [41, 36, 43],
        [44, 38, 26]]])

In [136]:
np.delete(thrD,0, axis = 1)

array([[[87, 74, 93],
        [17, 85, 75]],

       [[95, 71, 40],
        [83, 74, 68]],

       [[41, 36, 43],
        [44, 38, 26]]])

In [138]:
np.delete(thrD,1, axis = 2)

array([[[56, 70],
        [87, 93],
        [17, 75]],

       [[69, 11],
        [95, 40],
        [83, 68]],

       [[17, 55],
        [41, 43],
        [44, 26]]])

### Converte arrays

In [144]:
thrD

array([[[56, 37, 70],
        [87, 74, 93],
        [17, 85, 75]],

       [[69, 79, 11],
        [95, 71, 40],
        [83, 74, 68]],

       [[17, 10, 55],
        [41, 36, 43],
        [44, 38, 26]]])

In [147]:
one_d = thrD.reshape(-1,order = 'F') # Columwise  # 3D to 1D 
one_d

array([56, 69, 17, 87, 95, 41, 17, 83, 44, 37, 79, 10, 74, 71, 36, 85, 74,
       38, 70, 11, 55, 93, 40, 43, 75, 68, 26])

In [150]:
one_d = thrD.reshape(-1,order = 'c') # row wise  #3D to 1D
one_d

array([56, 37, 70, 87, 74, 93, 17, 85, 75, 69, 79, 11, 95, 71, 40, 83, 74,
       68, 17, 10, 55, 41, 36, 43, 44, 38, 26])

In [151]:
thrD

array([[[56, 37, 70],
        [87, 74, 93],
        [17, 85, 75]],

       [[69, 79, 11],
        [95, 71, 40],
        [83, 74, 68]],

       [[17, 10, 55],
        [41, 36, 43],
        [44, 38, 26]]])

### 3D to 2D

In [154]:
two_dim = thrD.reshape(9,3)
two_dim

array([[56, 37, 70],
       [87, 74, 93],
       [17, 85, 75],
       [69, 79, 11],
       [95, 71, 40],
       [83, 74, 68],
       [17, 10, 55],
       [41, 36, 43],
       [44, 38, 26]])

In [153]:
two_dim.ndim

2

In [156]:
two_dim = thrD.reshape((9,3),order = 'F')
two_dim

array([[56, 37, 70],
       [69, 79, 11],
       [17, 10, 55],
       [87, 74, 93],
       [95, 71, 40],
       [41, 36, 43],
       [17, 85, 75],
       [83, 74, 68],
       [44, 38, 26]])

In [157]:
two_dim = thrD.reshape((9,3),order = 'C')
two_dim

array([[56, 37, 70],
       [87, 74, 93],
       [17, 85, 75],
       [69, 79, 11],
       [95, 71, 40],
       [83, 74, 68],
       [17, 10, 55],
       [41, 36, 43],
       [44, 38, 26]])

In [1]:
import numpy as np

# 1D array: A simple list of elements
array_1d = np.array([1, 2, 3, 4])
print("1D Array:")
print(array_1d)

# 2D array: A list of lists (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array_2d)

# 3D array: A list of lists of lists (cube)
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("\n3D Array:")
print(array_3d)

# 4D array: A list of lists of lists of lists (hypercube)
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\n4D Array:")
print(array_4d)


1D Array:
[1 2 3 4]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
